#!/bin/bash

echo "📊 Database Seed Summary"
echo "========================"
echo ""
echo "Current seed includes:"
echo ""
echo "✅ Core Data:"
echo "   - 1 System Admin"
echo "   - 1 Organization (Demo Retail Store)"
echo "   - 2 Branches (Main + Downtown)"
echo "   - 4 Users (Boss, Manager, 2 Cashiers)"
echo ""
echo "✅ Business Data:"
echo "   - 2 Suppliers"
echo "   - 5 Products (Rice, Sugar, Oil, Milk, Bread)"
echo "   - 2 Customers"
echo "   - 1 Purchase transaction"
echo "   - 2 Sales transactions"
echo ""
echo "✅ Advanced Features:"
echo "   - 1 Promotion (Weekend Special)"
echo "   - 1 Purchase Order"
echo "   - 2 Expenses (Rent + Utilities)"
echo "   - 1 Task"
echo "   - 2 Notifications"
echo "   - 1 Message"
echo "   - 1 Employee record"
echo ""
echo "🔑 Login Credentials:"
echo "   Admin: admin@akariza.com / admin123"
echo "   Boss: boss@store.com / boss123"
echo "   Manager: manager@store.com / manager123"
echo "   Cashier: cashier@store.com / cashier123"
echo ""
echo "🚀 API Base URL: http://localhost:5000/api"
echo ""
echo "📝 To add more data, you can:"
echo "   1. Use the API endpoints to create more records"
echo "   2. Modify prisma/seed.ts and run: npx prisma db seed"
echo "   3. Use Prisma Studio: npx prisma studio"
echo ""
